; PlatformIO Project Configuration File
;
; Build del node emissor LoRa per a l'hort.
; Targeta: TTGO LoRa32 v2.1 (868 MHz, OLED integrat)

[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200

; Llibreries
lib_deps =
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    olikraus/U8g2@^2.35.19
    jgromes/RadioLib@^5.6.0

; Optimitzacions per deep sleep i baix consum
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_TTGO_LoRa32_V21
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DCONFIG_LOG_COLORS=1

; Partició optimitzada
board_build.partitions = min_spiffs.csv

; Velocitat de pujada
upload_speed = 921600
